version: '3'
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
    restart: always
    volumes:
      - /home/node/app/node_modules
      - ./react-app:/home/node/app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # bind mount the application code
      - instancedata:/app/instance  # use a named volume for the instance directory
    restart: always

volumes:
  instancedata:
