version: '3'
services:

  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - '6379:6379'
    restart: on-failure

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - frontend
      - backend
    restart: on-failure

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - WDS_SOCKET_PORT
    restart: on-failure
    volumes:
      - /home/node/app/node_modules
      - ./react-app:/home/node/app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app  # bind mount the application code
      - instancedata:/app/instance  # use a named volume for the instance directory
    restart: on-failure
    depends_on:
      - redis

volumes:
  instancedata:
