version: '3'
services:
  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    restart: always
    volumes:
      - /home/node/app/node_modules
      - ./react-app:/home/node/app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    restart: always
