version: '3'
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
    restart: always
    volumes:
      - /home/node/app/node_modules
      - ./react-app:/home/node/app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY
      - DATABASE_URL
      - SCHEMA
      - REACT_APP_BASE_URL
      - S3_BUCKET
      - S3_KEY
      - S3_SECRET
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/app  # bind mount the application code
      - instancedata:/app/instance  # use a named volume for the instance directory
    restart: always

volumes:
  instancedata:
