version: '3'
services:

  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - '6379:6379'

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - WDS_SOCKET_PORT
    restart: always
    volumes:
      - /home/node/app/node_modules
      - ./react-app:/home/node/app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY
      - DATABASE_URL
      - SCHEMA
      - REACT_APP_BASE_URL
      - S3_BUCKET
      - S3_KEY
      - S3_SECRET
      - FLASK_APP
      - FLASK_ENV
      - FLASK_DEBUG
      - FLASK_RUN_HOST
      - WDS_SOCKET_PORT
      - REDIS_HOST
      - REDIS_PORT
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - SMACK_ADMIN
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
    volumes:
      - .:/app  # bind mount the application code
      - instancedata:/app/instance  # use a named volume for the instance directory
    restart: always
    depends_on:
      - redis

volumes:
  instancedata:
