"""Adding some indices

Revision ID: 81e2a1ad2573
Revises: 0e01812d6ce4
Create Date: 2023-12-27 10:07:22.343574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e2a1ad2573'
down_revision = '0e01812d6ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_users_channels_id'), ['channels_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_users_users_id'), ['users_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_channel_id'), ['channel_id'], unique=False)

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reactions_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_reactions_message_id'))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_channel_id'))

    with op.batch_alter_table('channel_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_users_users_id'))
        batch_op.drop_index(batch_op.f('ix_channel_users_channels_id'))

    # ### end Alembic commands ###
