"""Indexes for channel dm/privacy status

Revision ID: 007711183e90
Revises: 567e5c9dd613
Create Date: 2023-12-28 08:23:53.088754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007711183e90'
down_revision = '567e5c9dd613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channels_is_direct'), ['is_direct'], unique=False)
        batch_op.create_index(batch_op.f('ix_channels_is_private'), ['is_private'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channels_is_private'))
        batch_op.drop_index(batch_op.f('ix_channels_is_direct'))

    # ### end Alembic commands ###
